// <auto-generated />
namespace WebAPIDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addUniqueIndexState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUniqueIndexState));
        
        string IMigrationMetadata.Id
        {
            get { return "201802190427087_addUniqueIndexState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
